name: video_player_elinux
description: Flutter plugin for displaying inline video with other Flutter widgets on Embedded Linux.
version: 1.0.0
homepage: https://github.com/geosat-rd/flutter-elinux-plugins
repository: https://github.com/geosat-rd/flutter-elinux-plugins/tree/main/packages/video_player

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.2.1

flutter:
  plugin:
    platforms:
      elinux:
        pluginClass: VideoPlayerElinuxPlugin
        dartPluginClass: ELinuxVideoPlayer
